name: Hello-world-workflow

on: [push]
jobs:
  hello-world-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run a single line script
      run: echo "Hello Srija!"

    - name: Run a multi-line script
      run: |
        echo "This is a simple example for github actions"
        echo "Workflow will start executing whenever there's a push event happens to the repository"
        echo "The repository has been checked out and this script is executing."
